config/routes.rb
Rails.application.routes.draw do

devise_for :users
  root 'groups#index'

  resources :users, only: [:edit,:update]
  resources :groups, except: [:destroy,:show, ] do
    resources :messages, only: [:index,:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :messages
  validates :group_name, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
belongs_to :user
belongs_to :group

end

app/models/message.rb
class Message < ApplicationRecord

  validates :body_or_image, presence: true

  belongs_to :user
  belongs_to :group
  mount_uploader :image, ImageUploader
  private
    def body_or_image
      body.presence || image.presence
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :members
has_many :groups, through: :members
has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  devise_parameter_sanitizer.permit(:account_update, keys: [:name])

  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = current_user.groups.order("created_at DESC")
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
      if @group.save
        redirect_to root_path,notice: "グループの作成に成功しました"
      else
        render :new
      end

  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: "グループを編集しました"
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:group_name, user_ids:[])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

def index
  @group = Group.find(params[:group_id])
  @groups = current_user.groups.order("created_at DESC")
  @message = Message.new
  @messages = Message.where(group_id: params[:group_id]).order("created_at ASC")
end

def create
  @groups = current_user.groups
  @message = current_user.messages.new(message_params)
  if @message.save
    respond_to do |format|
      format.html {redirect_to group_messages_path}
      format.json
    end
  else
    redirect_to group_messages_path, alert: "メッセージを入力してください。"
  end
end

private
def message_params
  params.require(:message).permit(:body,:image).merge(group_id: params[:group_id])
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


def edit
end

def update
  user = current_user
  current_user.update(update_params)
  redirect_to root_path
end

private
  def update_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper


end

app/views/groups/_chat-side.html.haml
.chat-side
  .chat-side__header
    %h5
      = current_user.name
      .font-awesome
        = link_to new_group_path, class: "font-awesome__specific" do
          %i{class: "fa fa-pencil-square-o"}
        = link_to edit_user_registration_path, class: "font-awesome__specific" do
          %i{class: "fa fa-cog"}
  .group
    %ul.group__list
      - @groups.each do |group|
        %li.group__name
          = link_to "#{group.group_name}", group_messages_path(group)
          - if group.messages.present?
            .group__message
              - if group.messages.last.image.present?
                画像が送信されました。
              - elsif group.messages.last.body.present?
                = group.messages.last.body
              - elsif group.messages.nil?
                まだ、メッセージが投稿されていません。

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        %h2
          1件のエラーが発生しました。
          %ul
            %li エラーです
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :group_name,"グループ名", class: "chat-group-form_label"
      .chat-group-form__field--right
        = f.text_field :group_name, placeholder: "グループ名を入力してください", class: "chat-group-form__input"
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
        </div>
        <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
        <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
        </div>
        <div id='user-search-result'></div>
        </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label "チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.collection_check_boxes(:user_ids, User.all, :id, :name)
        =f.submit "Save",class: "chat-group-form__action-btn"

app/views/groups/index.html.haml
.chat
  = render partial: "chat-side"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        %h2
          1件のエラーが発生しました。
          %ul
            %li エラーです
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :group_name,"グループ名", class: "chat-group-form_label"
      .chat-group-form__field--right
        = f.text_field :group_name,placeholder: "グループ名を入力してください", class: "chat-group-form__input"
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
        </div>
        <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
        <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
        </div>
        <div id='user-search-result'></div>
        </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label "チャットメンバー", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.collection_check_boxes(:user_ids, User.all, :id, :name)
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
        /
          <div id='chat-group-users'>
          <div class='chat-group-user clearfix' id='chat-group-user-22'>
          <input name='chat_group[user_ids][]' type='hidden' value='22'>
          <p class='chat-group-user__name'>seo_kyohei</p>
          </div>
          </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        =f.submit "Save",class: "chat-group-form__action-btn"

        / %input.chat-group-form__action-btn{"data-disable-with" => "Save", :name => "commit", :type => "submit", :value => "Save"}/

app/views/layouts/_flash.html.haml
- flash.each do |key,value|
  = content_tag(:div, value, class: "#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    =render partial:'layouts/flash'
  = yield

app/views/messages/_message.html.haml
- @messages.each do |message|
  %ul.chat-messages
    %li.chat-message
      .chat-message__header
        %p.chat-message__user
          = message.user.name
        %p.chat-message__date
          = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
        %p.chat-message__text
          = message.body
          = image_tag message.image_url(:thumb) if message.image.present?

app/views/messages/index.html.haml
.chat
  = render "groups/chat-side"
  / .chat-side
  /   .chat-side__header
  /     %h5
  /       = current_user.name
  /       .font-awesome
  /         = link_to root_path, class: "font-awesome__specific" do
  /           %i{class: "fa fa-pencil-square-o"}
  /         = link_to edit_user_registration_path, class: "font-awesome__specific" do
  /           %i{class: "fa fa-cog"}
  /   .group
  /     %ul.group__list
  /       - @groups.each do |group|
  /         %li.group__name
  /           = group.group_name
  /           .group__message
  /             メッセージはありません
  .chat-main
    .chat-header
      .chat-header__left
        %h2
          = @group.group_name
        %p.chat-header__members
          Members:
          - @group.users.each do |user|
            = user.name
      .chat-header__right
        = link_to "Edit", edit_group_path(@group), class: "chat-header__edit"
    .chat-body
      - if @messages
        = render partial: 'messages/message', local: @messages
      / %ul.chat-messages
      /   %li.chat-message
      /     .chat-message__header
      /       %p.chat-message__user
      /         = current_user.name
      /       %p.chat-message__date
      /         = @messages.created_at.strftime("%Y年%m月%d日 %H時%M分")
      /       %p.chat-message__text
      /         = @messages.body
    .chat-footer
      = form_for [@group, @message], html: {id: "new_message"} do |f|
        .chat-footer__form
          = f.text_area :body, placeholder: "Type a message",class: "chat-footer__input"
          = f.label :image do
            %i{class: "fa fa-picture-o file__icon"}
            = f.file_field :image, class: "file-picture",style: "display:none"
          = f.submit "Send", class:"chat-footer__submit"